### ISSUE TITLE
Installation issue: MongoDB/Backend is unavailable

### ISSUE THREAD

**Issue by phesami** [VertaAI/modeldb#281]
I am trying to install ModelDB on MACOS using docker compose. The installation halts at some point printing out the followings:
mongo_1     | 2018-02-08T01:52:59.432+0000 I NETWORK  [thread1] waiting for connections on port 27017
backend_1   | MongoDB is unavailable - sleeping
frontend_1  | Backend is unavailable - sleeping
backend_1   | MongoDB is unavailable - sleeping
frontend_1  | Backend is unavailable - sleeping

Any help is appreciated!

**Comment by justinanderson** [comment]
That sounds like a networking issue between the containers. Could you share the output of each of these commands run while in that unavailable state?

```
sw_vers
docker -v
docker-compose -v
docker-compose exec backend mongo mongo/foo --eval "db.getCollectionNames()"
docker-compose exec backend ping mongo
docker-compose exec backend ping frontend
docker network ls
```

**Comment by phesami** [comment]
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

docker -v
Docker version 17.12.0-ce, build c97c6d6

docker-compose -v
docker-compose version 1.18.0, build 8dd22a9

docker-compose exec backend mongo mongo/foo --eval "db.getCollectionNames()"
MongoDB shell version v3.4.11
connecting to: mongodb://foo:27017/mongo
2018-02-08T18:21:19.001+0000 I NETWORK  [thread1] getaddrinfo("foo") failed: Name or service not known
2018-02-08T18:21:19.001+0000 E QUERY    [thread1] Error: couldn't initialize connection to host foo, address is invalid :
connect@src/mongo/shell/mongo.js:240:13
@(connect):1:6
exception: connect failed

docker-compose exec backend ping mongo
PING mongo (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.143 ms
64 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=0.205 ms
64 bytes from 172.18.0.2: icmp_seq=2 ttl=64 time=0.121 ms

docker-compose exec backend ping frontend
PING frontend (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: icmp_seq=0 ttl=64 time=0.128 ms
64 bytes from 172.18.0.4: icmp_seq=1 ttl=64 time=0.221 ms
64 bytes from 172.18.0.4: icmp_seq=2 ttl=64 time=0.122 ms
64 bytes from 172.18.0.4: icmp_seq=3 ttl=64 time=0.217 ms
64 bytes from 172.18.0.4: icmp_seq=4 ttl=64 time=0.216 ms

docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
d27882e7ce24        bridge              bridge              local
f7dd8c69ea8e        host                host                local
e28e901d7940        modeldb             bridge              local
0dc0f5f6cb4e        modeldb_default     bridge              local
073cef482aa9        none                null                local
```

**Comment by justinanderson** [comment]
Aha, there's [a bug in Mongo 3.4.11](https://jira.mongodb.org/browse/SERVER-31437?_ga=2.183156198.1115913522.1518114823-1641319296.1490638468) that makes it interpret the `mongo/foo` as `foo/mongo`. That's fixed in 3.4.12, which was luckily just released on Docker Hub 19 hours ago.

If you update to the latest Mongo 3.4 image and recreate your Docker containers, you'll get a running ModelDB:

```
docker pull mongo:3.4
docker-compose down
docker-compose up
```

Please let me know if this works for you.

**Comment by phesami** [comment]
Still seeing the same issue. This time I see this:
```
phesami-mac:modeldb phesami$ docker-compose exec backend mongo mongo/foo --eval "db.getCollectionNames()"
MongoDB shell version v3.4.11
connecting to: mongodb://foo:27017/mongo
2018-02-08T21:42:00.511+0000 I NETWORK  [thread1] getaddrinfo("foo") failed: Name or service not known
2018-02-08T21:42:00.511+0000 E QUERY    [thread1] Error: couldn't initialize connection to host foo, address is invalid :
connect@src/mongo/shell/mongo.js:240:13
@(connect):1:6
exception: connect failed
```
And if I change it to foo/mongo I see this:
```
phesami-mac:modeldb phesami$ docker-compose exec backend mongo foo/mongo --eval "db.getCollectionNames()"
MongoDB shell version v3.4.11
connecting to: mongodb://mongo:27017/foo
MongoDB server version: 3.4.12
[ ]
```
the server version is 3.4.12 but the shell version is still 3.4.11! Any idea how to upgrade the shell version through docker?

**Comment by justinanderson** [comment]
Oh, right. You'll need to rebuild the modeldb backend image as well. That would still be using the 3.4.11 release of the mongodb-org-shell package. Try:

```
docker-compose build --no-cache backend
docker-compose down
docker-compose up
```

**Comment by phesami** [comment]
Thank you. That fixed the mongoDB issue. Now the installaion get stuck at this stage and doesn't proceed:
```
backend_1   | [edu.mit.csail.db.ml.main.Main.main()] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
mongo_1     | 2018-02-09T01:14:50.255+0000 I NETWORK  [thread1] connection accepted from 172.18.0.4:49984 #2 (1 connection now open)
mongo_1     | 2018-02-09T01:14:50.263+0000 I NETWORK  [conn2] received client metadata from 172.18.0.4:49984 conn2: { driver: { name: "mongo-java-driver", version: "3.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.9.60-linuxkit-aufs" }, platform: "Java/Oracle Corporation/1.8.0_151-8u151-b12-1~deb9u1-b12" }
backend_1   | [cluster-ClusterId{value='5a7cf60a2ab79c000194542b', description='null'}-mongo:27017] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:2}] to mongo:27017
backend_1   | [cluster-ClusterId{value='5a7cf60a2ab79c000194542b', description='null'}-mongo:27017] INFO org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 12]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=585155}
backend_1   | Starting the simple server on port 6543...
frontend_1  | Backend is up - executing command
frontend_1  | 
frontend_1  | > modeldb-vis@0.0.0 start /modeldb/frontend
frontend_1  | > node ./bin/www "--host" "backend"
frontend_1  | 
```

**Comment by phesami** [comment]
Thank you. That fixed it!
